### Basic Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kachirisky
  name: k8-nginx
spec:
  selector:
    matchLabels:
      app: k8-nginx
  template:
    metadata:
      labels:
        app: k8-nginx
    spec:
      containers:
      - image: ikachiriskys/k8-nginx
        name: k8-nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 10m
            memory: 8Mi
          requests:
            cpu: 10m
            memory: 8Mi
# Uncomment this if you're using the dockerhub secret
#      imagePullSecrets:
#      - name: my-pull-secret