apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: kachirisky
spec:
  volumes:
    - name: html
      emptyDir: {}

  containers:
    - name: nginx
      image: ikachiriskys/k8-nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/

    - name: sidecar-container
      image: alpine
      command: ["sh","-c","apk update;apk add curl;while true; do curl https://catfact.ninja/fact > /usr/share/nginx/html/index.html; sleep 5; done"]
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/